site_name: Duc Jeremy | Portfolio
site_url: https://github.com/jijiduc/portfolio/
repo_url: https://github.com/Toys-R-Us-Rex/Duckify
repo_name: Duckify

theme:
  name: material
  language: fr
  palette: 
    # Mode sombre par defaut (c'est plus classe)
    - scheme: slate 
      primary: teal
      accent: cyan
  features:
    - navigation.tabs # Menu horizontal pro
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition # Pour les notes, avertissements, etc.
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex: # Pour vos formules LaTeX
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
